### PR TITLE
renames and removed imports

### LINKED ISSUE #25: Rename `CYgray` to `cy-gray`

### PR DESCRIPTION
**Pull request by garrett-huggins**
- changed CYgray to cy-gray
- changed MyApp to App
- removed any unused imports
closes #25

### CODE REVIEW

**Comment by ryanlalchand** [comment]
what the hell i couldn't rename it without ESLint or TS yelling at me

**Review by JoeDuncko — CHANGES_REQUESTED** [review]
Looks like `CYgray` is used in two other places

**Comment by garrett-huggins** [comment]
> Looks like `CYgray` is used in two other places

got it, managed to find 3

**Review by JoeDuncko — APPROVED** [review]
LGTM!

**Pull request merged**
